[elasticsearch]
cloud_id=
api_key=

[database]
host=mysql-igsr-web
port=4641
user=g1krw
password=XXXXX
name=igsr_website_v2

# PROD
[site]
site_root=https://www.internationalgenome.org
site_base=https://www.internationalgenome.org

# used by sitemap indexer
# site_root: where to fetch from
# site_base: what to publish in the output docs
# DEV
# [site]
# site_root=http://localhost:8080
# site_base=http://localhost:8080