## --- PROD ---
[elasticsearch]
cloud_id=prj-ext-prod-gaa-igsr: ...
api_key=

[database]
host=mysql-igsr-web
port=XXXXX
user=XXXXX
password=XXXXX
name=igsr_website_v2

[site]
site_root=https://www.internationalgenome.org
site_base=https://www.internationalgenome.org

## --- DEV ---
; [elasticsearch]
; cloud_id=prj-ext-dev-gaa-igsr: ...
; api_key=

; [database]
; host=mysql-igsr-web
; port=XXXXX
; user=XXXXX
; password=XXXXX
; name=igsr_website_v2_test

; [site]
; site_root=https://www.test.internationalgenome.org
; site_base=https://www.test.internationalgenome.org